version: 2

updates:
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/app/Scripts"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
